[package]
name = "client-desktop"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
client-core = { path = "../client-core" }
common = { path = "../common" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
urlencoding = { workspace = true }
anyhow = { workspace = true }
inotify = { workspace = true }
filetime = { workspace = true }
mime_guess = { workspace = true }
notify-rust = { workspace = true }

[dev-dependencies]
tempfile = "3"
